[workspace]
members = ["dijavu", "dijavu_macros"]
resolver = "2"

[workspace.package]
edition = "2024"
license = "MIT"
readme = "README.md"
repository = "https://codeberg.org/jungnik/dijavu"

[workspace.dependencies]
rustc-hash = "2"
ctor = "1"
anyhow = "1"
futures = "0.3"
dijavu_macros = { path = "dijavu_macros", version = "0.0.1" }

syn = "2"
darling = "0.23"
proc-macro2 = "1"
quote = "1"
